name: template
description: Base template for all Flutter projects.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2"
  flutter: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animations: ^2.0.7
  # Date and Time
  intl: ^0.17.0
  # Console Log
  colorize: ^3.0.0
  # State management
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  # Localizations
  flutter_localizations:
    sdk: flutter
  # Local APIs
  locale_api:
    path: packages/locale_api
  theme_api:
    path: packages/theme_api
  universal_file:
    path: packages/universal_file

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true