name: universal_file
description: file management for different platform

version: 1.0.0+1

environment:
  sdk: ">=2.18.2"
  flutter: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.21.4
  mockito: ^5.3.2
  build_runner: ^2.3.0

flutter:
  uses-material-design: true
